services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: ["python", "main.py"]

  frontend:
    build:
      context: ./capra-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
